/*train*/
delete from train_t;
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('6d0ec350-7d2a-4e82-9826-4bdba742d9a0', 'Android初级开发', 'Android入门', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('1', 'Android高级开发', 'Android高阶编程', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('2', 'Android游戏开发', '塔防手游', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('3', 'IOS初级开发', '企业APP', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('4', 'IOS高级开发', '移动支付', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('5', 'IOS游戏开发', '3d游戏开发', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('6', '.NET初级开发', '', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('7', '.NET高级开发', '', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('8', 'JAVA初级开发', '', '');
INSERT INTO train_t (id, name, student_desc, train_desc) VALUES ('9', 'JAVA高级开发', '', '');


/*train_class*/
delete from train_class_t;
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('1', '6d0ec350-7d2a-4e82-9826-4bdba742d9a0', '500', '900', 2, 50, 'x-2231', '东软金融实施部', 'hello', '南京', '今天', '面向东软金融实施部', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('2', '6d0ec350-7d2a-4e82-9826-4bdba742d9a0', '400', '1000', 5, 30, 'x-2231', '豌豆荚', 'hello', '南京', '今天', '豌豆荚直招', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('3', '6d0ec350-7d2a-4e82-9826-4bdba742d9a0', '600', '750', 10, 40, 'x-2231', '小米', 'hello', '南京', '今天', '小米实习机会', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('4', '1', '700', '2000', 2, 20, 'x-2231', '腾讯', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('5', '1', '500', '1500', 4, 25, 'x-2231', '阿里', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('6', '1', '500', '1500', 6, 30, 'x-2231', '支付宝', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('7', '2', '500', '1800', 8, 35, 'x-2231', '百度', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('8', '2', '500', '1900', 10, 40, 'x-2231', '平安保险', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('9', '2', '500', '1100', 15, 45, 'x-2231', '车联网', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('10', '3', '500', '1200', 20, 50, 'x-2231', '京东', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('11', '3', '500', '1300', 2, 50, 'x-2231', '易讯', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('12', '3', '500', '1400', 2, 50, 'x-2231', '大众点评', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('13', '4', '500', '1600', 2, 50, 'x-2231', '格瓦拉', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('14', '4', '500', '900', 2, 50, 'x-2231', '上海移动', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('15', '4', '500', '850', 2, 50, 'x-2231', '上海电信', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('16', '5', '500', '1200', 2, 50, 'x-2231', '上海联通', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('17', '5', '500', '1300', 2, 50, 'x-2231', '北京移动', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('18', '5', '500', '1400', 2, 50, 'x-2231', '北京电信', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('19', '6', '500', '1500', 2, 50, 'x-2231', '北京联通', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('20', '7', '500', '1600', 2, 50, 'x-2231', '驴妈妈', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('21', '8', '500', '1700', 2, 50, 'x-2231', '携程', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');
INSERT INTO train_class_t (id, train_id, price, vip_price, current_student, total_student, serial_num, purpose_org, time_range, workspace, in_place_time, description, requirement, obtain, become) VALUES ('22', '9', '500', '1800', 2, 50, 'x-2231', '艺龙', 'hello', '南京', '今天', '测试', '测试', '测试', '测试');